sudo: required

language: node_js

node_js:
  - "6.9"

services:
  - docker

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - "curl https://install.meteor.com | /bin/sh"

before_script:
  - ssh-keyscan -H -t rsa,dsa $HOST >> ~/.ssh/known_hosts

script:
  - meteor npm run test
  - meteor npm run apptest

#after_success:
#  - if [ $TRAVIS_BRANCH == 'master' ]; then
#    /bin/sh fullDeploy.sh;
#    fi

deploy:
  skip_cleanup: true
  provider: script
  script: /bin/sh fullDeploy.sh
  on:
    branch: master