sudo: required

language: node_js

node_js:
  - "4"

before_install:
  - "curl -L http://git.io/3l-rRA | /bin/sh"

env:
  - CXX=g++-4.8 LAIKA_OPTIONS="-t 5000"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8