sudo: required

language: node_js

node_js:
  - "4"

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - "curl https://install.meteor.com | /bin/sh"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    sh dockerBuild.sh;
    sh productionDeploy.sh;
    fi

env:
  - CXX=g++-4.8