sudo: required

language: node_js

node_js:
  - "4"

services:
  - docker

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - sshpass

before_install:
  - "curl https://install.meteor.com | /bin/sh"

after_success:
  - if [ $TRAVIS_BRANCH == 'master' ] ; then
    /bin/sh fullDeploy.sh;
    fi

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: fullDeploy.sh
#  on:
#    branch: master