sudo: required
dist: trusty

language: node_js

node_js:
  - "4"

services:
  - docker

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - "curl https://install.meteor.com | /bin/sh"

before_script:
  - "ssh-keyscan -H -t rsa,dsa $HOST >> ~/.ssh/known_hosts"

script:
  - meteor npm run unittest
  - meteor npm run apptest

#deploy:
#  skip_cleanup: true
#  provider: script
#  script: ./scripts/deploy-travis.sh
#  on:
#    branch: master