version: '2.3'

services:
  database:
    build: ./.deploy/mongo
    image: dgacitua/mongo
    restart: on-failure
    ports:
      - 1313:27017
    volumes:
      - ${NEURONE_MONGO_PATH:-~/neuroneDatabase}:/data/db
    environment:
      - MONGODB_ADMIN_USER=${NEURONE_ADMIN_DB_USER:-admin}
      - MONGODB_ADMIN_PASS=${NEURONE_ADMIN_DB_PASS:-neurone2017}
      - MONGODB_APPLICATION_DATABASE=${NEURONE_DB:-neurone}
      - MONGODB_APPLICATION_USER=${NEURONE_DB_USER:-neurone}
      - MONGODB_APPLICATION_PASS=${NEURONE_DB_PASS:-neurone2017}
  search:
    image: solr:6.5
    restart: on-failure
    ports:
      - 1314:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - neurone
  app:
    build: 
      context: .
      args:
        username: ${NEURONE_USERNAME:-neurone}
        userid: ${NEURONE_USERID:-9001}
    image: dgacitua/neurone
    restart: on-failure
    cpu_percent: 50
    memswap_limit: 768m
    ports:
     - 80:80
    volumes:
     - ${NEURONE_ASSET_PATH:-~/neuroneAssets}:/assets
    links:
     - database
     - search
    environment:
     - ROOT_URL=http://${NEURONE_HOST:-localhost}
     - MONGO_URL=mongodb://${NEURONE_DB_USER:-neurone}:${NEURONE_DB_PASS:-neurone2017}@database:27017/${NEURONE_DB:-neurone}
     - NEURONE_SOLR_HOST=search
     - NEURONE_SOLR_PORT=8983
     - NEURONE_SOLR_CORE=neurone
     - DISABLE_WEBSOCKETS=0